/*
Descripción: Ventana Impuestos del Proyecto
Fecha: 26/Junio/2022
Nombre: David Enrique Garcia Olvera
 */
package vista;

/**
 *
 * @author David García
 */
public class Impuestos extends javax.swing.JFrame{

    public Impuestos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfiguracion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblImpuestos = new javax.swing.JLabel();
        btnConfHome = new javax.swing.JButton();
        checkImpuestos = new javax.swing.JCheckBox();
        comboPaisImpuesto = new javax.swing.JComboBox<>();
        panelImpuestos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaImpuestos = new javax.swing.JTable();
        btnNuevoImpuesto = new javax.swing.JButton();
        btnDesactivarImpuesto = new javax.swing.JButton();
        panelModImpuesto = new javax.swing.JPanel();
        txtModImpuesto = new javax.swing.JTextField();
        lblImpuesto = new javax.swing.JLabel();
        comboTipoImpuesto = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        spinnerPorcentaje = new javax.swing.JSpinner();
        lblPercent = new javax.swing.JLabel();
        btnGuardarImpuesto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVentas = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        menuProveedores = new javax.swing.JMenu();
        menuInventario = new javax.swing.JMenu();
        menuConfiguracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración");

        lblConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblConfiguracion.setText("Configuración");

        lblImpuestos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImpuestos.setText("Impuestos");

        btnConfHome.setText("Mostrar todas las opciones");
        btnConfHome.setToolTipText("");

        checkImpuestos.setText("Mis productos manejan impuestos (IVA, etc) y me encuentro en:");

        comboPaisImpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "México", "Otro" }));

        tablaImpuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaImpuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaImpuestos.setEnabled(false);
        tablaImpuestos.setFocusable(false);
        tablaImpuestos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaImpuestos.setShowGrid(false);
        jScrollPane1.setViewportView(tablaImpuestos);

        javax.swing.GroupLayout panelImpuestosLayout = new javax.swing.GroupLayout(panelImpuestos);
        panelImpuestos.setLayout(panelImpuestosLayout);
        panelImpuestosLayout.setHorizontalGroup(
            panelImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelImpuestosLayout.setVerticalGroup(
            panelImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImpuestosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        btnNuevoImpuesto.setText("Agregar Nuevo Impuesto");

        btnDesactivarImpuesto.setText("Desactivar");

        panelModImpuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelModImpuesto.setName(""); // NOI18N

        txtModImpuesto.setEditable(false);
        txtModImpuesto.setEnabled(false);

        lblImpuesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblImpuesto.setText("Impuesto");
        lblImpuesto.setEnabled(false);

        comboTipoImpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impuesto al Valor Agregado (IVA)", "Impuesto Sobre Hospedaje (ISH)", "Impuesto Especial sobre Productos y Servicio (IEPS)" }));
        comboTipoImpuesto.setSelectedIndex(-1);
        comboTipoImpuesto.setToolTipText("");
        comboTipoImpuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboTipoImpuesto.setEnabled(false);
        comboTipoImpuesto.setFocusable(false);

        lblPorcentaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPorcentaje.setText("Porcentaje");
        lblPorcentaje.setEnabled(false);

        spinnerPorcentaje.setEnabled(false);

        lblPercent.setText("%");
        lblPercent.setEnabled(false);

        btnGuardarImpuesto.setText("Guardar Impuesto");
        btnGuardarImpuesto.setEnabled(false);

        javax.swing.GroupLayout panelModImpuestoLayout = new javax.swing.GroupLayout(panelModImpuesto);
        panelModImpuesto.setLayout(panelModImpuestoLayout);
        panelModImpuestoLayout.setHorizontalGroup(
            panelModImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModImpuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelModImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModImpuesto)
                    .addGroup(panelModImpuestoLayout.createSequentialGroup()
                        .addComponent(lblPorcentaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPercent)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarImpuesto))
                    .addGroup(panelModImpuestoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblImpuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelModImpuestoLayout.setVerticalGroup(
            panelModImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModImpuestoLayout.createSequentialGroup()
                .addComponent(txtModImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuesto)
                    .addComponent(comboTipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModImpuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentaje)
                    .addComponent(spinnerPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPercent)
                    .addComponent(btnGuardarImpuesto))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        menuVentas.setText("Ventas");
        jMenuBar1.add(menuVentas);

        menuClientes.setText("Clientes");
        jMenuBar1.add(menuClientes);

        menuProductos.setText("Productos");
        jMenuBar1.add(menuProductos);

        menuProveedores.setText("Proveedores");
        jMenuBar1.add(menuProveedores);

        menuInventario.setText("Inventario");
        jMenuBar1.add(menuInventario);

        menuConfiguracion.setText("Configuración");
        jMenuBar1.add(menuConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDesactivarImpuesto)
                                    .addComponent(btnNuevoImpuesto)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkImpuestos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPaisImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addComponent(panelModImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 376, Short.MAX_VALUE))
                    .addComponent(lblConfiguracion)
                    .addComponent(lblImpuestos)
                    .addComponent(btnConfHome))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfHome)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImpuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkImpuestos)
                            .addComponent(comboPaisImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoImpuesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDesactivarImpuesto))))
                    .addComponent(panelModImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConfHome;
    public javax.swing.JButton btnDesactivarImpuesto;
    public javax.swing.JButton btnGuardarImpuesto;
    public javax.swing.JButton btnNuevoImpuesto;
    public javax.swing.JCheckBox checkImpuestos;
    private javax.swing.JComboBox<String> comboPaisImpuesto;
    public javax.swing.JComboBox<String> comboTipoImpuesto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfiguracion;
    public javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblImpuestos;
    public javax.swing.JLabel lblPercent;
    public javax.swing.JLabel lblPorcentaje;
    public javax.swing.JMenu menuClientes;
    public javax.swing.JMenu menuConfiguracion;
    public javax.swing.JMenu menuInventario;
    public javax.swing.JMenu menuProductos;
    public javax.swing.JMenu menuProveedores;
    public javax.swing.JMenu menuVentas;
    private javax.swing.JPanel panelImpuestos;
    private javax.swing.JPanel panelModImpuesto;
    public javax.swing.JSpinner spinnerPorcentaje;
    public javax.swing.JTable tablaImpuestos;
    public javax.swing.JTextField txtModImpuesto;
    // End of variables declaration//GEN-END:variables
}
