/*
 * Descripccion: VENTANA MODIFICAR PROVEEDOR
 * Alumno: JOSÉ LUIS ROCHA LÓPEZ
 * Fecha: 26/06/2022
 */
package vista;

/**
 *
 * @author Ching
 */
public class modificarprovedor extends javax.swing.JFrame {

    /**
     * Creates new form nuevoprovedor
     */
    public modificarprovedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        LBModificarProveedor = new javax.swing.JLabel();
        LBNombreProveedor = new javax.swing.JLabel();
        LBidProveedor = new javax.swing.JLabel();
        TXTIDproveedor = new javax.swing.JTextField();
        TXTnombreProveedor = new javax.swing.JTextField();
        TXTTelefonoProveedor = new javax.swing.JTextField();
        LBproveedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        TXTRFCproveedor = new javax.swing.JTextField();
        LBRFCproveedor = new javax.swing.JLabel();
        TXTCalleNumeroProveedor = new javax.swing.JTextField();
        LBCalleYNumero = new javax.swing.JLabel();
        BTTNuevoProveedor = new javax.swing.JButton();
        BTTModificarProveedor = new javax.swing.JButton();
        BTTEliminarProveedor = new javax.swing.JButton();
        LBTelefonosPro = new javax.swing.JLabel();
        BTTBuscar = new javax.swing.JButton();
        LBTipoTelefono = new javax.swing.JLabel();
        TXTCorreoProveedor = new javax.swing.JTextField();
        LBCorreoPro = new javax.swing.JLabel();
        BTTModificar = new javax.swing.JButton();
        TXTDepartamentoTelefono = new javax.swing.JTextField();
        LBDepartamento = new javax.swing.JLabel();
        TXTNombrePersonal = new javax.swing.JTextField();
        LBPersonalDepartamento = new javax.swing.JLabel();
        BOXTipoTelefono = new javax.swing.JComboBox<>();
        BOXColonia = new javax.swing.JComboBox<>();
        BOXEstado = new javax.swing.JComboBox<>();
        BOXMunicipio = new javax.swing.JComboBox<>();
        LBMunicipio = new javax.swing.JLabel();
        LBColonia = new javax.swing.JLabel();
        LBEstado = new javax.swing.JLabel();
        BTTActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnMenuVentas = new javax.swing.JMenu();
        BtnMenuClientes = new javax.swing.JMenu();
        BtnMenuProductos = new javax.swing.JMenu();
        BtnMenuProveedores = new javax.swing.JMenu();
        BtnMenuInventario = new javax.swing.JMenu();
        BtnMenuConfiguracion = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Proveedor");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBModificarProveedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LBModificarProveedor.setForeground(new java.awt.Color(255, 153, 102));
        LBModificarProveedor.setText("MODIFICAR PROVEEDOR");
        getContentPane().add(LBModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        LBNombreProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBNombreProveedor.setText("Nombre");
        getContentPane().add(LBNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 61, -1));

        LBidProveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBidProveedor.setText("IdProveedor");
        getContentPane().add(LBidProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        getContentPane().add(TXTIDproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 136, 111, -1));
        getContentPane().add(TXTnombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 256, -1));
        getContentPane().add(TXTTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, -1));

        LBproveedor.setText("PROVEEDORES");
        getContentPane().add(LBproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 590, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 590, 10));
        getContentPane().add(TXTRFCproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 225, 256, -1));

        LBRFCproveedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBRFCproveedor.setText("RFC");
        getContentPane().add(LBRFCproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 229, 61, -1));
        getContentPane().add(TXTCalleNumeroProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 256, -1));

        LBCalleYNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBCalleYNumero.setText("Calle Y numero");
        getContentPane().add(LBCalleYNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, -1));

        BTTNuevoProveedor.setText("Nuevo");
        getContentPane().add(BTTNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        BTTModificarProveedor.setText("Modificar");
        BTTModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTModificarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(BTTModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        BTTEliminarProveedor.setText("Eliminar");
        getContentPane().add(BTTEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        LBTelefonosPro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBTelefonosPro.setText("Telefonos");
        getContentPane().add(LBTelefonosPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, -1));

        BTTBuscar.setText("Buscar");
        getContentPane().add(BTTBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 134, 90, 30));

        LBTipoTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBTipoTelefono.setText("Tipo");
        getContentPane().add(LBTipoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 40, 20));
        getContentPane().add(TXTCorreoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 256, -1));

        LBCorreoPro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBCorreoPro.setText("Correo");
        getContentPane().add(LBCorreoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 58, 40));

        BTTModificar.setText("Modificar");
        getContentPane().add(BTTModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 220, 34));
        getContentPane().add(TXTDepartamentoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 260, -1));

        LBDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBDepartamento.setText("Departamento");
        getContentPane().add(LBDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 40));
        getContentPane().add(TXTNombrePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 260, -1));

        LBPersonalDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBPersonalDepartamento.setText("Personal Departamento");
        getContentPane().add(LBPersonalDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 40));

        BOXTipoTelefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(BOXTipoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 80, -1));

        BOXColonia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(BOXColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 70, -1));

        BOXEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(BOXEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 50, -1));

        BOXMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(BOXMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 60, -1));

        LBMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBMunicipio.setText("Municipio");
        getContentPane().add(LBMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 70, -1));

        LBColonia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBColonia.setText("Colonia");
        getContentPane().add(LBColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 70, -1));

        LBEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LBEstado.setText("Estado");
        getContentPane().add(LBEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 70, -1));

        BTTActualizar.setText("Actualizar");
        getContentPane().add(BTTActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 120, 120));

        BtnMenuVentas.setText("Ventas");
        jMenuBar1.add(BtnMenuVentas);

        BtnMenuClientes.setText("Clientes");
        jMenuBar1.add(BtnMenuClientes);

        BtnMenuProductos.setText("Productos");
        jMenuBar1.add(BtnMenuProductos);

        BtnMenuProveedores.setText("Proveedores");
        jMenuBar1.add(BtnMenuProveedores);

        BtnMenuInventario.setText("Inventario");
        jMenuBar1.add(BtnMenuInventario);

        BtnMenuConfiguracion.setText("Configuracion");
        jMenuBar1.add(BtnMenuConfiguracion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTTModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTModificarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTTModificarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarprovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
       //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarprovedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> BOXColonia;
    public javax.swing.JComboBox<String> BOXEstado;
    public javax.swing.JComboBox<String> BOXMunicipio;
    public javax.swing.JComboBox<String> BOXTipoTelefono;
    public javax.swing.JButton BTTActualizar;
    public javax.swing.JButton BTTBuscar;
    public javax.swing.JButton BTTEliminarProveedor;
    public javax.swing.JButton BTTModificar;
    public javax.swing.JButton BTTModificarProveedor;
    public javax.swing.JButton BTTNuevoProveedor;
    public javax.swing.JMenu BtnMenuClientes;
    public javax.swing.JMenu BtnMenuConfiguracion;
    public javax.swing.JMenu BtnMenuInventario;
    public javax.swing.JMenu BtnMenuProductos;
    public javax.swing.JMenu BtnMenuProveedores;
    public javax.swing.JMenu BtnMenuVentas;
    private javax.swing.JLabel LBCalleYNumero;
    private javax.swing.JLabel LBColonia;
    private javax.swing.JLabel LBCorreoPro;
    private javax.swing.JLabel LBDepartamento;
    private javax.swing.JLabel LBEstado;
    private javax.swing.JLabel LBModificarProveedor;
    private javax.swing.JLabel LBMunicipio;
    private javax.swing.JLabel LBNombreProveedor;
    private javax.swing.JLabel LBPersonalDepartamento;
    private javax.swing.JLabel LBRFCproveedor;
    private javax.swing.JLabel LBTelefonosPro;
    public javax.swing.JLabel LBTipoTelefono;
    private javax.swing.JLabel LBidProveedor;
    private javax.swing.JLabel LBproveedor;
    public javax.swing.JTextField TXTCalleNumeroProveedor;
    public javax.swing.JTextField TXTCorreoProveedor;
    public javax.swing.JTextField TXTDepartamentoTelefono;
    public javax.swing.JTextField TXTIDproveedor;
    public javax.swing.JTextField TXTNombrePersonal;
    public javax.swing.JTextField TXTRFCproveedor;
    public javax.swing.JTextField TXTTelefonoProveedor;
    public javax.swing.JTextField TXTnombreProveedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
