/*
 * Descripcion: Ventana para agregar un nuevo producto al catalogo
 * Fecha: 24-06-2022
 * Autor: Quiroz Vega Kevin Alexis
 * 
 */
package vista;

/**
 *
 * @author Tanya
 */
public class NuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public NuevoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaNuevoProducto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        etiquetaProductos1 = new javax.swing.JLabel();
        etiquetaCodigoProducto = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        etiquetaDescripcion = new javax.swing.JLabel();
        etiquetaSeVende = new javax.swing.JLabel();
        cbPerecedero = new javax.swing.JCheckBox();
        cbUnidades = new javax.swing.JCheckBox();
        etiquetaPrecioCosto = new javax.swing.JLabel();
        txtPrecioCosto = new javax.swing.JTextField();
        etiquetaGanancia = new javax.swing.JLabel();
        etiquetaDepartamento = new javax.swing.JLabel();
        etiquetaHay = new javax.swing.JLabel();
        txtHay = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        etiquetaMinimo = new javax.swing.JLabel();
        txtMaximo = new javax.swing.JTextField();
        etiquetaMaximo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        etiquetaAtiende = new javax.swing.JLabel();
        txtGanancia = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        LblNombreProducto = new javax.swing.JLabel();
        txtNombreProd = new javax.swing.JTextField();
        cbKilo = new javax.swing.JCheckBox();
        txtProveedor = new javax.swing.JTextField();
        etiquetaDescripcion1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnMenuVentas = new javax.swing.JMenu();
        BtnMenuClientes = new javax.swing.JMenu();
        BtnMenuProductos = new javax.swing.JMenu();
        BtnMenuProveedores = new javax.swing.JMenu();
        BtnMenuInventario = new javax.swing.JMenu();
        BtnMenuConfiguracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaNuevoProducto.setBackground(new java.awt.Color(255, 153, 51));
        etiquetaNuevoProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiquetaNuevoProducto.setForeground(new java.awt.Color(255, 153, 51));
        etiquetaNuevoProducto.setText("NUEVO PRODUCTO");
        getContentPane().add(etiquetaNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 24));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 665, 10));

        btnNuevo.setText("Nuevo");
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, -1, -1));

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 41, -1, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        btnDepartamentos.setText("Departamentos");
        getContentPane().add(btnDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnCatalogo.setText("Catalogo");
        getContentPane().add(btnCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 665, 10));

        etiquetaProductos1.setBackground(new java.awt.Color(255, 153, 51));
        etiquetaProductos1.setText("PRODUCTOS");
        getContentPane().add(etiquetaProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 91, 24));

        etiquetaCodigoProducto.setText("Codigo barras:");
        getContentPane().add(etiquetaCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 246, -1));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 230, -1));

        etiquetaDescripcion.setText("Descripcion:");
        getContentPane().add(etiquetaDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        etiquetaSeVende.setText("Se vende");
        getContentPane().add(etiquetaSeVende, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        cbPerecedero.setText("Perecedero");
        cbPerecedero.setAlignmentY(0.0F);
        cbPerecedero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerecederoActionPerformed(evt);
            }
        });
        getContentPane().add(cbPerecedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        cbUnidades.setText("Por unidades/pieza");
        cbUnidades.setAlignmentY(0.0F);
        getContentPane().add(cbUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        etiquetaPrecioCosto.setText("Precio compra:");
        getContentPane().add(etiquetaPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtPrecioCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioCostoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 230, -1));

        etiquetaGanancia.setText("Ganancia:");
        getContentPane().add(etiquetaGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        etiquetaDepartamento.setText("Departamento:");
        getContentPane().add(etiquetaDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        etiquetaHay.setText("Hay:");
        getContentPane().add(etiquetaHay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtHay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHayActionPerformed(evt);
            }
        });
        getContentPane().add(txtHay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 108, -1));

        txtMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 108, -1));

        etiquetaMinimo.setText("Minimo:");
        getContentPane().add(etiquetaMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        txtMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximoActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 108, -1));

        etiquetaMaximo.setText("Maximo:");
        getContentPane().add(etiquetaMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jLabel12.setText("%");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        etiquetaAtiende.setText("Lo atiende");
        getContentPane().add(etiquetaAtiende, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 4, -1, -1));

        txtGanancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGananciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtGanancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 70, -1));

        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 108, -1));

        LblNombreProducto.setText("Nombre producto:");
        getContentPane().add(LblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtNombreProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProdActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 250, -1));

        cbKilo.setText("Por kilogramos");
        cbKilo.setAlignmentY(0.0F);
        cbKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKiloActionPerformed(evt);
            }
        });
        getContentPane().add(cbKilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 230, -1));

        etiquetaDescripcion1.setText("Proveedor:");
        getContentPane().add(etiquetaDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        BtnMenuVentas.setText("Ventas");
        jMenuBar1.add(BtnMenuVentas);

        BtnMenuClientes.setText("Clientes");
        jMenuBar1.add(BtnMenuClientes);

        BtnMenuProductos.setText("Productos");
        jMenuBar1.add(BtnMenuProductos);

        BtnMenuProveedores.setText("Proveedores");
        jMenuBar1.add(BtnMenuProveedores);

        BtnMenuInventario.setText("Inventario");
        jMenuBar1.add(BtnMenuInventario);

        BtnMenuConfiguracion.setText("Configuracion");
        jMenuBar1.add(BtnMenuConfiguracion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void cbPerecederoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerecederoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPerecederoActionPerformed

    private void txtPrecioCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCostoActionPerformed

    private void txtHayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHayActionPerformed

    private void txtMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimoActionPerformed

    private void txtMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximoActionPerformed

    private void txtGananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGananciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGananciaActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void txtNombreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProdActionPerformed

    private void cbKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKiloActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NuevoProducto().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu BtnMenuClientes;
    public javax.swing.JMenu BtnMenuConfiguracion;
    public javax.swing.JMenu BtnMenuInventario;
    public javax.swing.JMenu BtnMenuProductos;
    public javax.swing.JMenu BtnMenuProveedores;
    public javax.swing.JMenu BtnMenuVentas;
    private javax.swing.JLabel LblNombreProducto;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCatalogo;
    public javax.swing.JButton btnDepartamentos;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JCheckBox cbKilo;
    public javax.swing.JCheckBox cbPerecedero;
    public javax.swing.JCheckBox cbUnidades;
    private javax.swing.JLabel etiquetaAtiende;
    private javax.swing.JLabel etiquetaCodigoProducto;
    private javax.swing.JLabel etiquetaDepartamento;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaDescripcion1;
    private javax.swing.JLabel etiquetaGanancia;
    private javax.swing.JLabel etiquetaHay;
    private javax.swing.JLabel etiquetaMaximo;
    private javax.swing.JLabel etiquetaMinimo;
    private javax.swing.JLabel etiquetaNuevoProducto;
    private javax.swing.JLabel etiquetaPrecioCosto;
    private javax.swing.JLabel etiquetaProductos1;
    private javax.swing.JLabel etiquetaSeVende;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtDepartamento;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtGanancia;
    public javax.swing.JTextField txtHay;
    public javax.swing.JTextField txtMaximo;
    public javax.swing.JTextField txtMinimo;
    public javax.swing.JTextField txtNombreProd;
    public javax.swing.JTextField txtPrecioCosto;
    public javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
